services:
  - type: web
    name: EasyStore-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

databases:
  - name: EasyStore-db
    databaseName: easystoredb
    plan: free
